global:
  scrape_interval: 2s   # How often to scrape targets (default is 1m)

scrape_configs:
  - job_name: "observability_app"
    static_configs:
      - targets: ["host.docker.internal:9090"]  # If running Docker on Mac/Win
        # OR ["localhost:8000"] if running Prometheus without Docker



